// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LayBody: typeof import('@layui/layui-vue')['LayBody']
    LayBreadcrumb: typeof import('@layui/layui-vue')['LayBreadcrumb']
    LayBreadcrumbItem: typeof import('@layui/layui-vue')['LayBreadcrumbItem']
    LayButton: typeof import('@layui/layui-vue')['LayButton']
    LayCol: typeof import('@layui/layui-vue')['LayCol']
    LayConfigProvider: typeof import('@layui/layui-vue')['LayConfigProvider']
    LayDropdown: typeof import('@layui/layui-vue')['LayDropdown']
    LayDropdownMenu: typeof import('@layui/layui-vue')['LayDropdownMenu']
    LayDropdownMenuItem: typeof import('@layui/layui-vue')['LayDropdownMenuItem']
    LayFooter: typeof import('@layui/layui-vue')['LayFooter']
    LayFullscreen: typeof import('@layui/layui-vue')['LayFullscreen']
    LayHeader: typeof import('@layui/layui-vue')['LayHeader']
    LayIcon: typeof import('@layui/icons-vue')['LayIcon']
    LayInput: typeof import('@layui/layui-vue')['LayInput']
    LayLayer: typeof import('@layui/layer-vue')['LayLayer']
    LayLayout: typeof import('@layui/layui-vue')['LayLayout']
    LayLine: typeof import('@layui/layui-vue')['LayLine']
    LayMenu: typeof import('@layui/layui-vue')['LayMenu']
    LayMenuItem: typeof import('@layui/layui-vue')['LayMenuItem']
    LayRow: typeof import('@layui/layui-vue')['LayRow']
    LaySubMenu: typeof import('@layui/layui-vue')['LaySubMenu']
    LaySwitch: typeof import('@layui/layui-vue')['LaySwitch']
    LayTab: typeof import('@layui/layui-vue')['LayTab']
    LayTabItem: typeof import('@layui/layui-vue')['LayTabItem']
    LayTransition: typeof import('@layui/layui-vue')['LayTransition']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
